### ISSUE TITLE
Testnet: No peers syncing agora-chain-testnet?

### ISSUE THREAD

**Issue by RoscoPColtrane1** [bosagora/agora-chain#25] opened 2022-11-20 14:55 UTC
Docker containers bosagora/agora-cl-node:v1.0.2 and bosagora/agora-el-node:v1.0.1 cant download full agora-chain on testnet.
i tried: 
./agora.sh el-node init
./agora.sh docker-compose up
i disabled agora-cl-validator (no keys yet)

Docker log agora-el-node:
- Last segment =:
"imported new chain segment               blocks=1203 txs=0    mgas=0.000  elapsed=635.218ms   mgasps=0.000  number=246,645 hash=ed6909..0c67bf age=3w5d17h"
- Then this happens:
"Legacy sync reached merge threshold      number=246,646 hash=bdadef..600e37 td=493,234 ttd=493,234" 
"Local chain is post-merge, waiting for beacon client sync switch-over..." 

Docker log agora-cl-node:
"level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0

Its syncing over 2 days now with same errors.

Neccesary ports are exposed to the internet.
Also no peers with this method './agora.sh el-node run' and './agora.sh cl-node run'
Mainnet chain is syncing just fine.
Why cant it find peers for testnet? mainnet works ok.
thx.

**Comment by MichaelKim20** [comment] 2022-11-21 07:19
In order to solve this issue, I will apply the contents below to Agora-cl first.
https://github.com/libp2p/go-libp2p/pull/1902

**Comment by RoscoPColtrane1** [comment] 2022-11-21 08:11
> In order to solve this issue, I will apply the contents below to Agora-cl first. [libp2p/go-libp2p#1902](https://github.com/libp2p/go-libp2p/pull/1902)

Thankyou MichealKim. Does testnet have an different version of libp2p than mainnet?
Im not behind a VPN.

some info:
Docker port of agora-cl and agora-el:
agora-cl
12000/udp -> 0.0.0.0:12000
12000/udp -> :::12000
13000/tcp -> 0.0.0.0:13000
13000/tcp -> :::13000

agora-el
8545/tcp -> 0.0.0.0:8545
8545/tcp -> :::8545
30303/tcp -> 0.0.0.0:30303
30303/tcp -> :::30303
30303/udp -> 0.0.0.0:30303
30303/udp -> :::30303

netstat:
udp        0      0 0.0.0.0:12000           0.0.0.0:*                           41463/docker-proxy
udp        0      0 0.0.0.0:30303           0.0.0.0:*                           41302/docker-proxy
udp6       0      0 :::12000                :::*                                41470/docker-proxy
udp6       0      0 :::30303                :::*                                41309/docker-proxy
tcp        0      0 0.0.0.0:13000           0.0.0.0:*               LISTEN      41441/docker-proxy
tcp        0      0 0.0.0.0:30303           0.0.0.0:*               LISTEN      41281/docker-proxy
tcp6       0      0 :::13000                :::*                    LISTEN      41447/docker-proxy
tcp6       0      0 :::30303                :::*                    LISTEN      41289/docker-proxy
tcp        0      0 0.0.0.0:8545            0.0.0.0:*               LISTEN      41323/docker-proxy
tcp6       0      0 :::8545                 :::*                    LISTEN      41330/docker-proxy

ports are open (except 8545)

**Comment by MichaelKim20** [comment] 2022-11-21 09:48
I think it's a VPN environment because it runs on a docker.
It works well in most cases.
After a few restarts, the peer is not found.

I've spent a lot of time solving this problem, but I haven't found it yet.
In this case, I changed the IP.

I'll continue to look for more solid solutions

**Comment by MichaelKim20** [comment] 2022-11-21 09:51
I have confirmed that this problem occurs even in an environment that does not use a docker. So I'll try other ways to solve this

**Comment by MichaelKim20** [comment] 2022-11-21 09:55
Did you delete the folder 'root/chain/' before you changed from mainnet to testnet?

**Comment by RoscoPColtrane1** [comment] 2022-11-21 10:15
> 
yes,
In ./agora.sh is a 'init' that removes the chain.
agora.sh also mounts the local directory '(pwd)./root/chain' to the container.  So testnet and mainnet store their own local chain in their own directory.

**Comment by MichaelKim20** [comment] 2022-11-21 12:15
Agora-cl was forked from Ethereum's consensus client, [prysmaticlabs/prysm](https://github.com/prysmaticlabs/prysm) version 3.1.1.
This issue has not yet been resolved for Prysm.
https://github.com/prysmaticlabs/prysm/issues/10920
The solution I have found so far is to change the IP.
Try this method for a while

We will reflect this issue as soon as it is resolved in Prysm.

**Comment by RoscoPColtrane1** [comment] 2022-11-21 12:25
ok, can you be a bit more specific? Which kind of IP do i need to change? Container or server?
thx.

**Comment by MichaelKim20** [comment] 2022-11-22 00:15
> ok, can you be a bit more specific? Which kind of IP do i need to change? Container or server? thx.

When I changed the IP of the server, the initial synchronization went well.

**Comment by MichaelKim20** [comment] 2022-11-22 08:39
I checked the following through the code below.

If you reconnect more than 5 times with the same IP, it will be judged as BadIP. And I can't connect with peers because the connection is terminated.

https://github.com/bosagora/agora-cl/blob/f274b1d26adc7ba3c77fe191cebf27e08b930b18/beacon-chain/p2p/peers/status.go#L905-L923

This implementation is thought to be a way to create a more stable and decentralized P2P network.
Therefore, we recommend that you do not restart after synchronizing the nodes.
And the only solution is to change the IP.

**Comment by MichaelKim20** [comment] 2022-11-22 11:24
https://github.com/bosagora/agora-chain/pull/31
Nodes are now good at finding peers and synchronizing well.

**Comment by RoscoPColtrane1** [comment] 2022-11-22 14:03
yes, you fixed it sir, thank you MichealKim 👍

**Closed as completed** 2022-11-22 14:04 UTC
