### ISSUE TITLE
docker-compose.yml missing ports 3500 and 4000 

### ISSUE THREAD

**Issue by RoscoPColtrane1** [bosagora/agora-chain#28] opened 2022-11-21 21:26 UTC
file docker-compose.yml missing ports 3500 and 4000 for agora-cl-node. See agora.sh 
 ports:
       - "13000:13000"
       - "12000:12000/udp"
       **- "3500:3500"
       - "4000:4000"**

**Comment by MichaelKim20** [comment] 2022-11-22 08:00
The ports 3500 and 4000 are used in the validator.
And if you don't do other services, you don't have to expose it to the outside world.
The validator of the docker-compose can also be connected using DNS inside the docker as shown below.

https://github.com/bosagora/agora-chain/blob/mainnet/docker-compose.yml#L45-L46

The ports 4000 needs to be left open to use the command `volatile-exit`.
Thank you.

**Comment by MichaelKim20** [comment] 2022-11-22 11:25
https://github.com/bosagora/agora-chain/pull/29
https://github.com/bosagora/agora-chain/pull/30

Added

**Comment by MichaelKim20** [comment] 2022-11-22 11:26
PR is merged and the issue is resolved and closes this.

**Closed as completed by MichaelKim20** 2022-11-22 11:26 UTC
